// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Configure Prisma to run the npm script when `npx prisma db seed` is executed
    seed: 'npm run prisma:seed',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
